//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovaTranslate_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentSpecialization
    {
        public int Id { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<int> IdSpecialization { get; set; }
    
        public virtual order order { get; set; }
        public virtual specialization specialization { get; set; }
    }
}
