//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovaTranslate_001.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sovadb001Entities0 : DbContext
    {
        public sovadb001Entities0()
            : base("name=sovadb001Entities0")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<document> documents { get; set; }
        public DbSet<documentSpecialization> documentSpecializations { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<price> prices { get; set; }
        public DbSet<queue> queues { get; set; }
        public DbSet<specialization> specializations { get; set; }
        public DbSet<translator> translators { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<WordsSpecialization> WordsSpecializations { get; set; }
    }
}
