//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovaTranslate_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.documents = new HashSet<document>();
            this.documentSpecializations = new HashSet<documentSpecialization>();
            this.queues = new HashSet<queue>();
        }
    
        public int IdOrder { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public System.DateTime dateOfCompletion { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public Nullable<int> idUser { get; set; }
        public bool isDone { get; set; }
        public Nullable<bool> inProgress { get; set; }
        public Nullable<double> totalCost { get; set; }
    
        public virtual ICollection<document> documents { get; set; }
        public virtual ICollection<documentSpecialization> documentSpecializations { get; set; }
        public virtual ICollection<queue> queues { get; set; }
        public virtual user user { get; set; }
    }
}
