//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovaTranslate_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public int IdPrice { get; set; }
        public int IdSpecialization { get; set; }
        public int IdTranslator { get; set; }
        public double price1 { get; set; }
    
        public virtual specialization specialization { get; set; }
        public virtual translator translator { get; set; }
    }
}
