//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovaTranslate_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialization
    {
        public specialization()
        {
            this.documentSpecializations = new HashSet<documentSpecialization>();
            this.prices = new HashSet<price>();
            this.WordsSpecializations = new HashSet<WordsSpecialization>();
        }
    
        public int IdSpecialization { get; set; }
        public string name { get; set; }
        public Nullable<int> complexity { get; set; }
        public Nullable<bool> isLanguage { get; set; }
    
        public virtual ICollection<documentSpecialization> documentSpecializations { get; set; }
        public virtual ICollection<price> prices { get; set; }
        public virtual ICollection<WordsSpecialization> WordsSpecializations { get; set; }
    }
}
