//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovaTranslate_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class translator
    {
        public translator()
        {
            this.prices = new HashSet<price>();
            this.queues = new HashSet<queue>();
        }
    
        public int IdTranslator { get; set; }
        public Nullable<int> reputation { get; set; }
        public Nullable<int> countOfComplitedOrders { get; set; }
        public int IdUser { get; set; }
    
        public virtual ICollection<price> prices { get; set; }
        public virtual ICollection<queue> queues { get; set; }
        public virtual user user { get; set; }
    }
}
