//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SovaTranslate_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordsSpecialization
    {
        public int Id { get; set; }
        public int IdSpecialization { get; set; }
        public string word { get; set; }
        public bool isWordSpecialization { get; set; }
        public int numberOfVisits { get; set; }
        public int languageId { get; set; }
    
        public virtual specialization specialization { get; set; }
    }
}
